name: e_commerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
  smooth_page_indicator: ^2.0.1
  get: ^4.7.3
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1
  readmore: ^3.0.0

  get_storage: ^2.1.1
  connectivity_plus: ^7.0.0

  #firebase
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.1
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo/black_app_logo.png
    - assets/logo/white_app_logo.png
    - assets/animations/
    - assets/images/
    - assets/logo/
    - assets/icons/categories/
    - assets/banners/
    - assets/products/
    - assets/brands/
    - assets/icons/payment_methods/


  uses-material-design: true

