// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMVvs3vMbZZgqw9wACPrix_Bi5oc5VMPk',
    appId: '1:571488214538:web:12205b85ce0847755509f3',
    messagingSenderId: '571488214538',
    projectId: 'e-commerce-app-43786',
    authDomain: 'e-commerce-app-43786.firebaseapp.com',
    storageBucket: 'e-commerce-app-43786.firebasestorage.app',
    measurementId: 'G-9GYDXRMDMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHCN-hsoZe0zK-JcZk3WDCj5nJuKS7s9w',
    appId: '1:571488214538:android:c35501056e1007545509f3',
    messagingSenderId: '571488214538',
    projectId: 'e-commerce-app-43786',
    storageBucket: 'e-commerce-app-43786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-o0nBOjPtnmgmMgvT46ztw1UxYOQ5DFA',
    appId: '1:571488214538:ios:67c43891e120b68e5509f3',
    messagingSenderId: '571488214538',
    projectId: 'e-commerce-app-43786',
    storageBucket: 'e-commerce-app-43786.firebasestorage.app',
    androidClientId: '571488214538-8lursghahs68f9huosgae8umqs55jlfv.apps.googleusercontent.com',
    iosClientId: '571488214538-q8d49r05ijbftdjl9nt325d1lf0pej7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
